version: '3.8'

services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - '5000:5000'
    env_file:
      - .env
    environment:
      - HUSKY=0
    depends_on:
      - postgres
      - redis
    networks:
      - internal_network

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - internal_network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge

volumes:
  postgres_data:
